/**
 * ./src/core/constants/state/types.js
 *
 */

export default {
  // app
  LOGGED_OUT: "LOGGED_OUT",
  LOGGED_IN: "LOGGED_IN",

  // Auth Notification
  NOTIFICATION_SUCCESS: 'NOTIFICATION_SUCCESS',
  NOTIFICATION_ERROR: 'NOTIFICATION_ERROR',
  NOTIFICATION_CLEAR: 'NOTIFICATION_CLEAR',

  // user
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  CLEAN_LOGIN_FORM: 'CLEAN_LOGIN_FORM',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT: 'LOGOUT',

  // users
  GETALL_REQUEST: 'USERS_GETALL_REQUEST',
  GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
  GETALL_FAILURE: 'USERS_GETALL_FAILURE',

  DELETE_REQUEST: 'USERS_DELETE_REQUEST',
  DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
  DELETE_FAILURE: 'USERS_DELETE_FAILURE',

  USER_UPDATED: "USER_UPDATED"
};